version: "3"
services:
  hello-world: 
    image: hello-world # Replace with your other docker services

  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports: 
      - "3000:3000"
      - "80:3000"