version: "3"
services:
  web:
    build: 
      context: ./
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "3000:3000"
      - "3001:3001"